export function renderDemoResult(result, options = {}) {
  if (isTerminalDemo(result?.type)) {
    return renderTerminalResult(result)
  }

  const artifacts = artifactsFromResult(result)
  if (!artifacts.length) {
    return { text: result?.message || 'Demo completed.', html: '' }
  }

  const escapedMessage = escapeHtml(result.message || `${artifacts.length} generated files are ready.`)
  const cards = artifacts.map((artifact) => renderArtifactCard(artifact, options)).join('')
  const html = `<p>${escapedMessage}</p>${cards}`
  return {
    text: `${artifacts.map((artifact) => artifact.fileName).join(', ')} generated by backend tool. Preview/download links are available.`,
    html
  }
}

export function artifactsFromResult(result) {
  if (Array.isArray(result?.artifacts) && result.artifacts.length) {
    return result.artifacts.filter(Boolean)
  }
  return result?.artifact ? [result.artifact] : []
}

export function formatBytes(size) {
  const value = Number(size || 0)
  if (value < 1024) return `${value} B`
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`
  return `${(value / 1024 / 1024).toFixed(1)} MB`
}

export function formatDate(value) {
  return value ? new Date(value).toLocaleString() : 'soon'
}

function renderArtifactCard(artifact, options) {
  const previewUrl = escapeHtml(absoluteUrl(artifact.previewUrl, options.baseUrl))
  const downloadUrl = escapeHtml(absoluteUrl(artifact.downloadUrl, options.baseUrl))
  const fileName = escapeHtml(artifact.fileName)
  const mimeType = escapeHtml(artifact.mimeType || '')
  const expires = escapeHtml(formatDate(artifact.expiresAt))
  return `
    <div class="artifact-result">
      <strong>${artifactTitle(artifact)}</strong>
      ${artifact.mimeType?.startsWith('image/') ? `<img src="${previewUrl}" alt="${fileName}" />` : ''}
      <div class="artifact-meta">
        <span>${fileName}</span>
        <span>${mimeType}</span>
        <span>${formatBytes(artifact.size)}</span>
        <span>Expires ${expires}</span>
      </div>
      <div class="artifact-actions">
        <a href="${previewUrl}" target="_blank" rel="noreferrer">Preview</a>
        <a href="${downloadUrl}" download="${fileName}" target="_blank" rel="noreferrer">Download</a>
      </div>
    </div>
  `
}

function renderTerminalResult(result) {
  const title = terminalTitle(result?.type)
  const message = result?.message || 'Command completed.'
  const summaryItems = summaryItemsFromResult(result)
  const statusClass = result?.status === 'error' ? 'error' : 'success'
  const cards = summaryItems.map((item) => {
    const state = summaryState(item.state)
    return `
      <article class="terminal-summary-card ${state}">
        <span>${escapeHtml(item.label || 'Summary')}</span>
        <strong>${escapeHtml(item.value || '')}</strong>
        ${item.detail ? `<small>${escapeHtml(item.detail)}</small>` : ''}
      </article>
    `
  }).join('')
  const rawOutput = escapeHtml(result?.terminalOutput || '')
  const raw = rawOutput
    ? `<details class="raw-output-panel"><summary>Raw output</summary><pre>${rawOutput}</pre></details>`
    : ''
  return {
    text: `${title}: ${message}\n${summaryItems.map((item) => `${item.label}: ${item.value}`).join('\n')}`,
    html: `
      <div class="terminal-demo-result">
        <div class="terminal-demo-head">
          <span class="terminal-status ${statusClass}">${escapeHtml(result?.status || 'success')}</span>
          <div>
            <strong>${escapeHtml(title)}</strong>
            <small>${escapeHtml(message)}</small>
          </div>
        </div>
        <div class="terminal-summary-grid">${cards}</div>
        ${raw}
      </div>
    `
  }
}

function summaryItemsFromResult(result) {
  if (Array.isArray(result?.summaryItems) && result.summaryItems.length) {
    return result.summaryItems.filter(Boolean)
  }
  return [{
    label: 'Result',
    value: result?.status === 'error' ? 'Needs attention' : 'Completed',
    detail: result?.message || '',
    state: result?.status === 'error' ? 'error' : 'success'
  }]
}

function terminalTitle(type) {
  const labels = {
    doctor: 'Wayfinder Doctor',
    terminal: 'Wayfinder Doctor',
    'backend-tests': 'Backend Targeted Tests',
    'java-runtime': 'Java Runtime Check',
    'maven-version': 'Maven Version Check'
  }
  return labels[type] || 'Engineering Command'
}

function summaryState(value) {
  return ['success', 'warning', 'error', 'info'].includes(value) ? value : 'info'
}

function isTerminalDemo(type) {
  return ['doctor', 'terminal', 'backend-tests', 'java-runtime', 'maven-version'].includes(type)
}

function artifactTitle(artifact) {
  if (artifact?.mimeType?.startsWith('image/')) return 'Generated Image'
  if (artifact?.mimeType === 'application/pdf') return 'Generated PDF'
  return 'Generated Text Artifact'
}

function absoluteUrl(path, baseUrl = '') {
  if (!path) return ''
  if (/^https?:\/\//.test(path)) return path
  const base = String(baseUrl || '').replace(/\/+$/, '')
  const joined = `${base}${path}`.replace(/([^:]\/)\/+/g, '$1')
  return new URL(joined, window.location.origin).href
}

function escapeHtml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
